CREATE TABLE IF NOT EXISTS orders (
    orderID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    userID INT NOT NULL,
    bookID INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    purchaseDate DATE NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(userID),
    FOREIGN KEY (bookID) REFERENCES library(bookID),
    FOREIGN KEY (price) REFERENCES library(price)
) AUTO_INCREMENT = 3001;